/////////////////////////////////////////////////////////////////////////////
//	テストプレイ

local args = ::arguments, i;

//	言語選択。workspaceから設定取ってきちゃうかな～
local ws = decodeJSON( FileRef( ".sakana.ws")?.load() || "{}");
local sysset = loadconf( "/data/setting.json");
local lt = chooseLanguage( ws["debuglang"] || sysset.projlang);
::lang = Language( lt);

module.hookAction( "conf_postload", @(){
	if( lang.code != sysset.projlang){
		local tres = getResource( `/data/trans/${lang.code}.trns`);
		if( tres){
			local trans = decodeJSON( tres.loadData());
			override( conf._map, trans.transdict, false);
		}
		local f = FileRef( "tmp/x.json");
		local bb = encodeJSON( conf._map, 5, ByteBuffer()); bb.pos = 0;
		f.save( bb);
	}
}, -100);

//	作業中のデータを復元。翻訳前に

if( (i=args.indexOf( "-wd")) >= 0){
	local wd = ObjectInput.decode( FileRef( args[i+1]).load());
	// printf( "WorkingData: %S\n", encodeJSON( wd, 5));
	module.hookAction( "conf_postload", @(){
		override( conf._map, wd["conf"], true);
		foreach( path, v in wd["res"]){
			local r = getResource( path);
			if( r){
				r.file = { load = @() v};	//	すごい
			}
		}
	}, -200);
}


//	テストプレイ環境はWindowsでProgram Files外にあるはずなので、カレント/savedataに保存する
::savedir <- FileRef( skGetCurrentDir().."/savedata"); ::savedir.mkdirs();

runsk( "/ClientConfig.sk");
::clientconf = ClientConfig.load();
if( !skGetScreenSize( [0,0])[0]){	//	skRestart時にはウィンドウは既にできている
	if( !clientconf.screen.fullscreen){
		local wh = clientconf.screen.reso_window.split( "x");	//	"1920x1080"のような文字列
		skCreateScreen( "RPG-Cobo TestPlay", int( wh[0]), int( wh[1]), 5|16);
	}else{
		local wh = clientconf.screen.reso_screen.split( "x");
		if( !skSupportsDisplaySize( int( wh[0]), int( wh[1]))) wh = ["1280","720"];
		skCreateScreen( "RPG-Cobo TestPlay", int( wh[0]), int( wh[1]), 0);
	}
}

skBeginRender();
skClearParam( #ClearParam( 0.0, 0.0, 0.0, 1.0));

runsk( "/load.sk");
if( ws["debugtouch"]) GPUI.emuosname <- "Android";		//	タッチデバッグの時はAndroidってことにする
::soundmanager.setBGMVolume( clientconf.sound.bgmvol * 0.008);	//	BGMはちょっと小さめに。。。
::soundmanager.setSEVolume( clientconf.sound.sevol * 0.012);	//	SEは大き目。。。


RPGMain.setupUI();
::rootview.setValue( "apptitle", conf.setting.title);
{
	local sc = skGetScreenSize( [0,0]);
	::rootview.stretchSize( sc[0], sc[1]);
}


//	ロゴから起動しない。設定を直に読み込んで
RPGMain.loadSetting();

local recfx = arguments.contains( "-recfx");	//	使用したシェーダーを記録
local prof = null;
if( ::arguments.contains( "-skprof")) (prof = SKProfiler()).start();

local applydebugpref(){
	if( ws["debugitems"]) rpgstat.addAllItems();
	if( ws["debuglv"]){
		foreach( p in rpgstat.playermap){
			if( p) p.setLV( ws.debuglv);
		}
	}
}


{
	local slot = -2;
	
	//	起動モードの判定
	if( (i=args.indexOf( "-slot")) >= 0){
		slot = int( args[i+1]);
	}
	switch( slot){
	case -2:	//	title
		if( !args.contains( "-map") && !args.contains( "-battle") && !args.contains( "-event")){
			RPGMain.goTitle();
			applydebugpref();
			goto SKIP;
		}
	case -1:	//	newgame
		(::rpgstat = RPGState()).newGame();
		local d = ::conf.setting.inimap;
		local sstat = ::rpgstat.stagemap[d.mapid] <- RPGStageState();
		sstat.enter( d.mapid, d, rpgvar.REMAPID);
		break;
	default:	//	save slot
		local f = RPGMain._savefile( slot);
		local ns = ObjectInput.decode( f.load());
		ns.saveslot = slot;
		ns.savetime = f.lastmodified;
		::rpgstat = ns;
		break;
	}
	applydebugpref();
	
	//	
	if( (i=args.indexOf( "-map")) >= 0){
		local mapid = args[i+1], pos = decodeJSON( args[i+2]);
		local portal = { mapid=mapid, pos=pos};
		local sstat = ::rpgstat.stagemap[mapid] <- RPGStageState();		//	RPGStageStateは毎回初期化。
		sstat.enter( mapid, portal, ++rpgvar.REMAPID);
		::rpgstat.mapid = mapid;
		local stg = RPGStage( rpgstat.mapid);
		stg.launch();
	}else
	if( (i=args.indexOf( "-battle")) >= 0){
		local emapid = args[i+1], gid = int( args[i+2]);
		local cmd = ::conf.map[emapid].encount.find( @( v) v.gid==gid);
		local mapid = cmd.mapid;
		local skillid = ((i=args.indexOf( "-skill")) >= 0) ? args[i+1] : null;
		local enemyid = ((i=args.indexOf( "-enemy")) >= 0) ? args[i+1] : null;
		if( enemyid){
			cmd.enemies[0].id = enemyid;
		}
		//	
		//	コマンドを拡張してマップ移動をバトルにする
		local cmd_ = {
			...cmd,	//	enemies, escape, bgm など必要な情報のために展開しておく
			//	マップ移動先指定
			dest = { mapid=cmd.mapid, pos=(8,null,8), },
			//	以下バトル起動用の関数類。
			startfunc = @( st, opt){	//	opt==cmd_自身
				st.battle = skillid? SkillTestBattleRunner( st, {...opt, skillid=skillid}) : RPGMain.createBattleRunner( ::conf.setting.battletype, st, opt);
				st.battle.start( st);
			},
			//	バトル終了時のコールバック
			endfunc = @( bt){
				skExit( 0);
			},
		};
		local sstat = ::rpgstat.stagemap[mapid];
		if( !sstat) sstat = ::rpgstat.stagemap[mapid] <- RPGStageState();
		sstat.enter( mapid, cmd_.dest, rpgvar.REMAPID);
		local stg = RPGStage( cmd_.mapid);
		stg.launch( cmd_);
	}else
	if( (i=args.indexOf( "-event")) >= 0){
		local mapid = args[i+1], evid = int( args[i+2]), evpage = int( args[i+3]);
		local map = ::conf.map[mapid], ev = map.event[evid], r = (ev.pos[3]+2)&3, v = Vector3D(0,0,-2).rotate( r*Math.PI/2, 0, 0).add( ev.pos).scale( 0.5);
		local portal = { mapid=mapid, pos=[v.x,v.y,v.z,r]};
		local sstat = ::rpgstat.stagemap[mapid] <- RPGStageState();
		sstat.enter( mapid, portal, ++rpgvar.REMAPID);
		::rpgstat.mapid = mapid;
		local stg = RPGStage( rpgstat.mapid);
		local cmd_ = {
			startfunc = @( st, opt){
				local p = ev.page[evpage];
				if( !p["pararun"]){	//	メインイベント実行
					st.mainevent = "MATTE";	
					newthread().start( @(){
						sleep( 300);
						st.mainevent = null;
						local ev = st.getEvent( evid);
						ev.forceTrigger( evpage)
					}, st);
				}
			},
		}
		stg.launch( cmd_);
	}else{
		local stg = RPGStage( rpgstat.mapid);
		stg.launch();
	}
SKIP:
	;
}

//	flush log
newthread().start( @(){
	for( ;;){
		flushStdOut(); suspend();
	}
}, this);

//	debug shortcut
import VirtualKeyCode;

local revertRenderSkip( s){
	local v = ::rootview.findChild( s);
	v.layerflags = v.layerflags ^ 0x8000;
}

local rootevent( e){
	if( e.id != KEY_PRESSED) return;
	switch( e.keycode){
	case VK_F2:
		revertRenderSkip( "info");
		revertRenderSkip( "stageui");
		revertRenderSkip( "message");
		revertRenderSkip( "menu");
		break;
	}
}

::rootview.addPostEventListener( KEY_EVENT, rootevent);


RPGMain.mainloop();

if( prof){
	prof.stop();
	local fs = FileRef( "log/prof.json").open( "w");
	prof.write( fs);
	fs.close();
}

//	使用したシェーダーを記録。gamemainのpreloaShaders()で読み込む。
if( recfx){
	local tecbits = {};
	local f = FileRef( skGetCodebase() .. "/resource/skfxload.json");
	if( f.exists()) tecbits = decodeJSON( f.load());	//	前回の結果を上書き。消えたシェーダーが残り続ける問題あり。
	foreach( efx in skFXGetEffects()){
		foreach( tec in efx){
			local tecname = tec.name, tb = tecbits[tecname] || [], bitsnum = 0;
			for( local l = 0; tec.getShaderSource( l); l ++){
				local ss = tec.getShaderSource( l);
				local sb = tb[l]; if( !sb) tb .. (sb=[]);
				foreach( bits in ss.getCompiledShaderBits()){
					if( sb.indexOf( bits) < 0) sb .. bits;
				}
				bitsnum += length( sb);
			}
			if( bitsnum){
				tecbits[tecname] <- tb;
			}
		}
	}
	local bb = encodeJSON( tecbits, 5, ByteBuffer());
	bb.pos = 0;
	f.save( bb);
}

skEndRender();
