//***LicenseHere

import VirtualKeyCode;
import ModifiersMask;
import PropertyType;
import RPGPropertyType;

local srcdir = dirname( callee().getSourceName());

////////////////////////////////////////////////////////////////////////////////
//	
//	ResEditorMapAsset : マップアセット
//	
//	

//	
class ResEditorMapAsset extends ResEditor
{
	static RESSLOTUI = "/ui/resslot3.ui";
	
	static props = [
		{ pid="name", lbl="$T.lbl_name", type=LANGSTRING, defval=null }
		{ pid="group", lbl="$T.lbl_group", type=LIST, list=@() ::conf._resource.map_asset._meta.groups.map( @( v)(
			{ lbl=v.name, icon=v.icon, val=v.id }
		))}
		{ pid="eventuse", lbl="$T.lbl_eventuse", type=BOOL, defval=false },
		{ pid="cntpos", lbl="$T.lbl_centerpos", type=VEC3, range=(0.0,1.0), q=100, defval=[0.5,0.0,0.5], hide=@( pl) !pl.getParam( "eventuse")},
		// { pid="mapcol", lbl="$T.lbl_mapcol", type=BOOL, defval=false, hide=@( pl) !pl.getParam( "eventuse")},
		{ pid="bw64", lbl="", type=CUSTOMBUTTON, tostring=@( v) "$T.lbl_editasset", cnt="cnt5.ui", icon="\ue745", ui="1",
			edit = @( val){
				::skstudio.editor.editSelectedAsset();
			}
		}
	];

	static titlelbl = "$T.lbl_resedit : $T.side_res_map_asset";
	
	function init( path){
		super.init( path);
	}

	//	作業中のデータでデバッグするための情報取得
	//	TODO : bw64は個々のマップエディタから取得される。ここにあるのは古いデータ。。。
	function getWorkingData(){
		local t = { conf={ _resource={ [res.name] = data}}};
		return t;
	}

	function isValidData( d){
		return !!d["bw64"];
	}
	
	function itemSelected( v){
		local d = v.data;
		if( !d) d = v.data = data[v.id] <- { name="", group=0, bw64=null};
		setDefaultProperties( props, d);
		//
		proplist.bindProperties( props);
		proplist.setParameters( d);
	}

	function editSelectedAsset(){
		local id = selitem.id, d = data[id];
		if( d.bw64){
			if( isFileChanged()){
				if( Dialogs.confirm( {msg="$T.confirm_save_befor_edit"})){
					op.markSaved();
					::skstudio.updateChangeFile( this);
					local _data = filterValidData( data);
					res.save( _data);	//	セーブ時にフィルター
				}else{
					return;
				}
			}
			::skstudio.openEditor( "/.x/map_asset/" .. id);
		}
	}

	function itemAction( e){
		editSelectedAsset();
	}

	function propevent( e){
		local cmd = e.actioncmd;
		if( cmd.cmd != "prop") return;
		local pid = cmd.prop.pid, val = cmd.val;
		switch( pid){
		default:
			setParamOp( selitem.id, cmd.prop, val);
			break;
		}
	}

	function showItemContextMenu( e){
		local menudata = [
			{ id="edit", lbl="$T.lbl_edit", icon="\ue745" },
			"-",
			{ id="copy", lbl="$T.menu_edit_copy", icon="\ue14d" },
			{ id="paste", lbl="$T.menu_edit_paste", icon="\ue14f"},
		]
		local ret = MenuPopup.run( menudata);
		switch( ret["id"]){
		case "edit":
			editSelectedAsset();
			break;
		case "copy":
			copy();
			break;
		case "paste":
			paste();
			break;
		}
	}
}

class ResEditorMapAsset.ResPreview extends ResourcePreviewCanvas
{
	resid = null;

	constructor( v, e){
		super( v, e);
	}

	function setResourceID( rid){
		// resid = rid;
		// local r = RPGResource.getResource( rid);
		// datamenu.setValue( "lbl", sprintf( "%S: %S", rid, lang( r.name)));
		// // view.setValue( "icon", r["icon"] || ConfigResource.dbiconmap[datatype]);
		// setResourceData( rid, r);
	}
}
